// <auto-generated />
namespace PP4.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class codefirst_11_12_2019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(codefirst_11_12_2019));
        
        string IMigrationMetadata.Id
        {
            get { return "201912120319177_codefirst_11_12_2019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
