// <auto-generated />
namespace PP4.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class CambiosCodeFirst27_11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambiosCodeFirst27_11));
        
        string IMigrationMetadata.Id
        {
            get { return "201911280616457_CambiosCodeFirst27_11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
