//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP4.ConsoleTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Identification del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPerson", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.AddPersonResponse AddPerson(PP4.ConsoleTest.ServiceReference1.AddPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddPersonResponse> AddPersonAsync(PP4.ConsoleTest.ServiceReference1.AddPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePerson", ReplyAction="*")]
        void DeletePerson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePerson", ReplyAction="*")]
        System.Threading.Tasks.Task DeletePersonAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Identification del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePerson", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.UpdatePersonResponse UpdatePerson(PP4.ConsoleTest.ServiceReference1.UpdatePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePerson", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.UpdatePersonResponse> UpdatePersonAsync(PP4.ConsoleTest.ServiceReference1.UpdatePersonRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetPersonResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPerson", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.GetPersonResponse GetPerson(PP4.ConsoleTest.ServiceReference1.GetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetPersonResponse> GetPersonAsync(PP4.ConsoleTest.ServiceReference1.GetPersonRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllPeopleResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPeople", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.GetAllPeopleResponse GetAllPeople(PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPeople", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetAllPeopleResponse> GetAllPeopleAsync(PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Description del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRoom", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.AddRoomResponse AddRoom(PP4.ConsoleTest.ServiceReference1.AddRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddRoomResponse> AddRoomAsync(PP4.ConsoleTest.ServiceReference1.AddRoomRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Description del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRoom", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.UpdateRoomResponse UpdateRoom(PP4.ConsoleTest.ServiceReference1.UpdateRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.UpdateRoomResponse> UpdateRoomAsync(PP4.ConsoleTest.ServiceReference1.UpdateRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRoom", ReplyAction="*")]
        void DeleteRoom(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRoom", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteRoomAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetRoomResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRoom", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.GetRoomResponse GetRoom(PP4.ConsoleTest.ServiceReference1.GetRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetRoomResponse> GetRoomAsync(PP4.ConsoleTest.ServiceReference1.GetRoomRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllRoomsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRooms", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.GetAllRoomsResponse GetAllRooms(PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRooms", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetAllRoomsResponse> GetAllRoomsAsync(PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AddScheduleResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSchedule", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.AddScheduleResponse AddSchedule(PP4.ConsoleTest.ServiceReference1.AddScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddScheduleResponse> AddScheduleAsync(PP4.ConsoleTest.ServiceReference1.AddScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSchedule", ReplyAction="*")]
        void UpdateSchedule(int ID_Schedule, System.DateTime Day, bool State);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateScheduleAsync(int ID_Schedule, System.DateTime Day, bool State);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSchedule", ReplyAction="*")]
        void DeleteSchedule(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteScheduleAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Description_Seat del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSeat", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.AddSeatResponse AddSeat(PP4.ConsoleTest.ServiceReference1.AddSeatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSeat", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddSeatResponse> AddSeatAsync(PP4.ConsoleTest.ServiceReference1.AddSeatRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Description_Seat del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSeat", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.UpdateSeatResponse UpdateSeat(PP4.ConsoleTest.ServiceReference1.UpdateSeatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSeat", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.UpdateSeatResponse> UpdateSeatAsync(PP4.ConsoleTest.ServiceReference1.UpdateSeatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSeat", ReplyAction="*")]
        void DeleteSeat(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSeat", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteSeatAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AddPurchaseResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPurchase", ReplyAction="*")]
        PP4.ConsoleTest.ServiceReference1.AddPurchaseResponse AddPurchase(PP4.ConsoleTest.ServiceReference1.AddPurchaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPurchase", ReplyAction="*")]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddPurchaseResponse> AddPurchaseAsync(PP4.ConsoleTest.ServiceReference1.AddPurchaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePurchase", ReplyAction="*")]
        void UpdatePurchase(int ID_Purchase, int ID_Batch, int ID_Person, System.DateTime Date_Purchase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePurchase", ReplyAction="*")]
        System.Threading.Tasks.Task UpdatePurchaseAsync(int ID_Purchase, int ID_Batch, int ID_Person, System.DateTime Date_Purchase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePurchase", ReplyAction="*")]
        void DeletePurchase(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePurchase", ReplyAction="*")]
        System.Threading.Tasks.Task DeletePurchaseAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPerson", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.AddPersonRequestBody Body;
        
        public AddPersonRequest() {
        }
        
        public AddPersonRequest(PP4.ConsoleTest.ServiceReference1.AddPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Identification;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        public AddPersonRequestBody() {
        }
        
        public AddPersonRequestBody(string Identification, string Name, string Mail, string Password) {
            this.Identification = Identification;
            this.Name = Name;
            this.Mail = Mail;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.AddPersonResponseBody Body;
        
        public AddPersonResponse() {
        }
        
        public AddPersonResponse(PP4.ConsoleTest.ServiceReference1.AddPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication.ServiceReference1.Person AddPersonResult;
        
        public AddPersonResponseBody() {
        }
        
        public AddPersonResponseBody(WebApplication.ServiceReference1.Person AddPersonResult) {
            this.AddPersonResult = AddPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePerson", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.UpdatePersonRequestBody Body;
        
        public UpdatePersonRequest() {
        }
        
        public UpdatePersonRequest(PP4.ConsoleTest.ServiceReference1.UpdatePersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Identification;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Password;
        
        public UpdatePersonRequestBody() {
        }
        
        public UpdatePersonRequestBody(int id, string Identification, string Name, string Mail, string Password) {
            this.id = id;
            this.Identification = Identification;
            this.Name = Name;
            this.Mail = Mail;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.UpdatePersonResponseBody Body;
        
        public UpdatePersonResponse() {
        }
        
        public UpdatePersonResponse(PP4.ConsoleTest.ServiceReference1.UpdatePersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdatePersonResponseBody {
        
        public UpdatePersonResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPerson", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.GetPersonRequestBody Body;
        
        public GetPersonRequest() {
        }
        
        public GetPersonRequest(PP4.ConsoleTest.ServiceReference1.GetPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetPersonRequestBody() {
        }
        
        public GetPersonRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.GetPersonResponseBody Body;
        
        public GetPersonResponse() {
        }
        
        public GetPersonResponse(PP4.ConsoleTest.ServiceReference1.GetPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication.ServiceReference1.Person GetPersonResult;
        
        public GetPersonResponseBody() {
        }
        
        public GetPersonResponseBody(WebApplication.ServiceReference1.Person GetPersonResult) {
            this.GetPersonResult = GetPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPeopleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPeople", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequestBody Body;
        
        public GetAllPeopleRequest() {
        }
        
        public GetAllPeopleRequest(PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPeopleRequestBody {
        
        public GetAllPeopleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPeopleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPeopleResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.GetAllPeopleResponseBody Body;
        
        public GetAllPeopleResponse() {
        }
        
        public GetAllPeopleResponse(PP4.ConsoleTest.ServiceReference1.GetAllPeopleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPeopleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication.ServiceReference1.Person[] GetAllPeopleResult;
        
        public GetAllPeopleResponseBody() {
        }
        
        public GetAllPeopleResponseBody(WebApplication.ServiceReference1.Person[] GetAllPeopleResult) {
            this.GetAllPeopleResult = GetAllPeopleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRoom", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.AddRoomRequestBody Body;
        
        public AddRoomRequest() {
        }
        
        public AddRoomRequest(PP4.ConsoleTest.ServiceReference1.AddRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Capacity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool State;
        
        public AddRoomRequestBody() {
        }
        
        public AddRoomRequestBody(string Description, int Capacity, bool State) {
            this.Description = Description;
            this.Capacity = Capacity;
            this.State = State;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.AddRoomResponseBody Body;
        
        public AddRoomResponse() {
        }
        
        public AddRoomResponse(PP4.ConsoleTest.ServiceReference1.AddRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication.ServiceReference1.Room AddRoomResult;
        
        public AddRoomResponseBody() {
        }
        
        public AddRoomResponseBody(WebApplication.ServiceReference1.Room AddRoomResult) {
            this.AddRoomResult = AddRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRoom", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.UpdateRoomRequestBody Body;
        
        public UpdateRoomRequest() {
        }
        
        public UpdateRoomRequest(PP4.ConsoleTest.ServiceReference1.UpdateRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_Room;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Capacity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool State;
        
        public UpdateRoomRequestBody() {
        }
        
        public UpdateRoomRequestBody(int ID_Room, string Description, int Capacity, bool State) {
            this.ID_Room = ID_Room;
            this.Description = Description;
            this.Capacity = Capacity;
            this.State = State;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.UpdateRoomResponseBody Body;
        
        public UpdateRoomResponse() {
        }
        
        public UpdateRoomResponse(PP4.ConsoleTest.ServiceReference1.UpdateRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateRoomResponseBody {
        
        public UpdateRoomResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoom", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.GetRoomRequestBody Body;
        
        public GetRoomRequest() {
        }
        
        public GetRoomRequest(PP4.ConsoleTest.ServiceReference1.GetRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetRoomRequestBody() {
        }
        
        public GetRoomRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.GetRoomResponseBody Body;
        
        public GetRoomResponse() {
        }
        
        public GetRoomResponse(PP4.ConsoleTest.ServiceReference1.GetRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication.ServiceReference1.Room GetRoomResult;
        
        public GetRoomResponseBody() {
        }
        
        public GetRoomResponseBody(WebApplication.ServiceReference1.Room GetRoomResult) {
            this.GetRoomResult = GetRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRoomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRooms", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequestBody Body;
        
        public GetAllRoomsRequest() {
        }
        
        public GetAllRoomsRequest(PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRoomsRequestBody {
        
        public GetAllRoomsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRoomsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.GetAllRoomsResponseBody Body;
        
        public GetAllRoomsResponse() {
        }
        
        public GetAllRoomsResponse(PP4.ConsoleTest.ServiceReference1.GetAllRoomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRoomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication.ServiceReference1.Room[] GetAllRoomsResult;
        
        public GetAllRoomsResponseBody() {
        }
        
        public GetAllRoomsResponseBody(WebApplication.ServiceReference1.Room[] GetAllRoomsResult) {
            this.GetAllRoomsResult = GetAllRoomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSchedule", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.AddScheduleRequestBody Body;
        
        public AddScheduleRequest() {
        }
        
        public AddScheduleRequest(PP4.ConsoleTest.ServiceReference1.AddScheduleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddScheduleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime Day;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool State;
        
        public AddScheduleRequestBody() {
        }
        
        public AddScheduleRequestBody(System.DateTime Day, bool State) {
            this.Day = Day;
            this.State = State;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddScheduleResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.AddScheduleResponseBody Body;
        
        public AddScheduleResponse() {
        }
        
        public AddScheduleResponse(PP4.ConsoleTest.ServiceReference1.AddScheduleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddScheduleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication.ServiceReference1.Schedule AddScheduleResult;
        
        public AddScheduleResponseBody() {
        }
        
        public AddScheduleResponseBody(WebApplication.ServiceReference1.Schedule AddScheduleResult) {
            this.AddScheduleResult = AddScheduleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSeatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSeat", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.AddSeatRequestBody Body;
        
        public AddSeatRequest() {
        }
        
        public AddSeatRequest(PP4.ConsoleTest.ServiceReference1.AddSeatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSeatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_Room;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description_Seat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Row;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Number;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal Price;
        
        public AddSeatRequestBody() {
        }
        
        public AddSeatRequestBody(int ID_Room, string Description_Seat, string Row, int Number, decimal Price) {
            this.ID_Room = ID_Room;
            this.Description_Seat = Description_Seat;
            this.Row = Row;
            this.Number = Number;
            this.Price = Price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSeatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSeatResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.AddSeatResponseBody Body;
        
        public AddSeatResponse() {
        }
        
        public AddSeatResponse(PP4.ConsoleTest.ServiceReference1.AddSeatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSeatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication.ServiceReference1.Seat AddSeatResult;
        
        public AddSeatResponseBody() {
        }
        
        public AddSeatResponseBody(WebApplication.ServiceReference1.Seat AddSeatResult) {
            this.AddSeatResult = AddSeatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSeatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSeat", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.UpdateSeatRequestBody Body;
        
        public UpdateSeatRequest() {
        }
        
        public UpdateSeatRequest(PP4.ConsoleTest.ServiceReference1.UpdateSeatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSeatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_Seat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_Room;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description_Seat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Row;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Number;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal Price;
        
        public UpdateSeatRequestBody() {
        }
        
        public UpdateSeatRequestBody(int ID_Seat, int ID_Room, string Description_Seat, string Row, int Number, decimal Price) {
            this.ID_Seat = ID_Seat;
            this.ID_Room = ID_Room;
            this.Description_Seat = Description_Seat;
            this.Row = Row;
            this.Number = Number;
            this.Price = Price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSeatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSeatResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.UpdateSeatResponseBody Body;
        
        public UpdateSeatResponse() {
        }
        
        public UpdateSeatResponse(PP4.ConsoleTest.ServiceReference1.UpdateSeatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateSeatResponseBody {
        
        public UpdateSeatResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPurchaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPurchase", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.AddPurchaseRequestBody Body;
        
        public AddPurchaseRequest() {
        }
        
        public AddPurchaseRequest(PP4.ConsoleTest.ServiceReference1.AddPurchaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPurchaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_Batch;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_Person;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Date_Purchase;
        
        public AddPurchaseRequestBody() {
        }
        
        public AddPurchaseRequestBody(int ID_Batch, int ID_Person, System.DateTime Date_Purchase) {
            this.ID_Batch = ID_Batch;
            this.ID_Person = ID_Person;
            this.Date_Purchase = Date_Purchase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPurchaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPurchaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public PP4.ConsoleTest.ServiceReference1.AddPurchaseResponseBody Body;
        
        public AddPurchaseResponse() {
        }
        
        public AddPurchaseResponse(PP4.ConsoleTest.ServiceReference1.AddPurchaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPurchaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication.ServiceReference1.Purchase AddPurchaseResult;
        
        public AddPurchaseResponseBody() {
        }
        
        public AddPurchaseResponseBody(WebApplication.ServiceReference1.Purchase AddPurchaseResult) {
            this.AddPurchaseResult = AddPurchaseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : PP4.ConsoleTest.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<PP4.ConsoleTest.ServiceReference1.WebService1Soap>, PP4.ConsoleTest.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.AddPersonResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.AddPerson(PP4.ConsoleTest.ServiceReference1.AddPersonRequest request) {
            return base.Channel.AddPerson(request);
        }
        
        public WebApplication.ServiceReference1.Person AddPerson(string Identification, string Name, string Mail, string Password) {
            PP4.ConsoleTest.ServiceReference1.AddPersonRequest inValue = new PP4.ConsoleTest.ServiceReference1.AddPersonRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.AddPersonRequestBody();
            inValue.Body.Identification = Identification;
            inValue.Body.Name = Name;
            inValue.Body.Mail = Mail;
            inValue.Body.Password = Password;
            PP4.ConsoleTest.ServiceReference1.AddPersonResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).AddPerson(inValue);
            return retVal.Body.AddPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddPersonResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.AddPersonAsync(PP4.ConsoleTest.ServiceReference1.AddPersonRequest request) {
            return base.Channel.AddPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddPersonResponse> AddPersonAsync(string Identification, string Name, string Mail, string Password) {
            PP4.ConsoleTest.ServiceReference1.AddPersonRequest inValue = new PP4.ConsoleTest.ServiceReference1.AddPersonRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.AddPersonRequestBody();
            inValue.Body.Identification = Identification;
            inValue.Body.Name = Name;
            inValue.Body.Mail = Mail;
            inValue.Body.Password = Password;
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).AddPersonAsync(inValue);
        }
        
        public void DeletePerson(int id) {
            base.Channel.DeletePerson(id);
        }
        
        public System.Threading.Tasks.Task DeletePersonAsync(int id) {
            return base.Channel.DeletePersonAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.UpdatePersonResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.UpdatePerson(PP4.ConsoleTest.ServiceReference1.UpdatePersonRequest request) {
            return base.Channel.UpdatePerson(request);
        }
        
        public void UpdatePerson(int id, string Identification, string Name, string Mail, string Password) {
            PP4.ConsoleTest.ServiceReference1.UpdatePersonRequest inValue = new PP4.ConsoleTest.ServiceReference1.UpdatePersonRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.UpdatePersonRequestBody();
            inValue.Body.id = id;
            inValue.Body.Identification = Identification;
            inValue.Body.Name = Name;
            inValue.Body.Mail = Mail;
            inValue.Body.Password = Password;
            PP4.ConsoleTest.ServiceReference1.UpdatePersonResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).UpdatePerson(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.UpdatePersonResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.UpdatePersonAsync(PP4.ConsoleTest.ServiceReference1.UpdatePersonRequest request) {
            return base.Channel.UpdatePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.UpdatePersonResponse> UpdatePersonAsync(int id, string Identification, string Name, string Mail, string Password) {
            PP4.ConsoleTest.ServiceReference1.UpdatePersonRequest inValue = new PP4.ConsoleTest.ServiceReference1.UpdatePersonRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.UpdatePersonRequestBody();
            inValue.Body.id = id;
            inValue.Body.Identification = Identification;
            inValue.Body.Name = Name;
            inValue.Body.Mail = Mail;
            inValue.Body.Password = Password;
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).UpdatePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.GetPersonResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.GetPerson(PP4.ConsoleTest.ServiceReference1.GetPersonRequest request) {
            return base.Channel.GetPerson(request);
        }
        
        public WebApplication.ServiceReference1.Person GetPerson(int id) {
            PP4.ConsoleTest.ServiceReference1.GetPersonRequest inValue = new PP4.ConsoleTest.ServiceReference1.GetPersonRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.GetPersonRequestBody();
            inValue.Body.id = id;
            PP4.ConsoleTest.ServiceReference1.GetPersonResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).GetPerson(inValue);
            return retVal.Body.GetPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetPersonResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.GetPersonAsync(PP4.ConsoleTest.ServiceReference1.GetPersonRequest request) {
            return base.Channel.GetPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetPersonResponse> GetPersonAsync(int id) {
            PP4.ConsoleTest.ServiceReference1.GetPersonRequest inValue = new PP4.ConsoleTest.ServiceReference1.GetPersonRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.GetPersonRequestBody();
            inValue.Body.id = id;
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).GetPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.GetAllPeopleResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.GetAllPeople(PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequest request) {
            return base.Channel.GetAllPeople(request);
        }
        
        public WebApplication.ServiceReference1.Person[] GetAllPeople() {
            PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequest inValue = new PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequestBody();
            PP4.ConsoleTest.ServiceReference1.GetAllPeopleResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).GetAllPeople(inValue);
            return retVal.Body.GetAllPeopleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetAllPeopleResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.GetAllPeopleAsync(PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequest request) {
            return base.Channel.GetAllPeopleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetAllPeopleResponse> GetAllPeopleAsync() {
            PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequest inValue = new PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.GetAllPeopleRequestBody();
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).GetAllPeopleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.AddRoomResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.AddRoom(PP4.ConsoleTest.ServiceReference1.AddRoomRequest request) {
            return base.Channel.AddRoom(request);
        }
        
        public WebApplication.ServiceReference1.Room AddRoom(string Description, int Capacity, bool State) {
            PP4.ConsoleTest.ServiceReference1.AddRoomRequest inValue = new PP4.ConsoleTest.ServiceReference1.AddRoomRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.AddRoomRequestBody();
            inValue.Body.Description = Description;
            inValue.Body.Capacity = Capacity;
            inValue.Body.State = State;
            PP4.ConsoleTest.ServiceReference1.AddRoomResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).AddRoom(inValue);
            return retVal.Body.AddRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddRoomResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.AddRoomAsync(PP4.ConsoleTest.ServiceReference1.AddRoomRequest request) {
            return base.Channel.AddRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddRoomResponse> AddRoomAsync(string Description, int Capacity, bool State) {
            PP4.ConsoleTest.ServiceReference1.AddRoomRequest inValue = new PP4.ConsoleTest.ServiceReference1.AddRoomRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.AddRoomRequestBody();
            inValue.Body.Description = Description;
            inValue.Body.Capacity = Capacity;
            inValue.Body.State = State;
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).AddRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.UpdateRoomResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.UpdateRoom(PP4.ConsoleTest.ServiceReference1.UpdateRoomRequest request) {
            return base.Channel.UpdateRoom(request);
        }
        
        public void UpdateRoom(int ID_Room, string Description, int Capacity, bool State) {
            PP4.ConsoleTest.ServiceReference1.UpdateRoomRequest inValue = new PP4.ConsoleTest.ServiceReference1.UpdateRoomRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.UpdateRoomRequestBody();
            inValue.Body.ID_Room = ID_Room;
            inValue.Body.Description = Description;
            inValue.Body.Capacity = Capacity;
            inValue.Body.State = State;
            PP4.ConsoleTest.ServiceReference1.UpdateRoomResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).UpdateRoom(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.UpdateRoomResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.UpdateRoomAsync(PP4.ConsoleTest.ServiceReference1.UpdateRoomRequest request) {
            return base.Channel.UpdateRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.UpdateRoomResponse> UpdateRoomAsync(int ID_Room, string Description, int Capacity, bool State) {
            PP4.ConsoleTest.ServiceReference1.UpdateRoomRequest inValue = new PP4.ConsoleTest.ServiceReference1.UpdateRoomRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.UpdateRoomRequestBody();
            inValue.Body.ID_Room = ID_Room;
            inValue.Body.Description = Description;
            inValue.Body.Capacity = Capacity;
            inValue.Body.State = State;
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).UpdateRoomAsync(inValue);
        }
        
        public void DeleteRoom(int id) {
            base.Channel.DeleteRoom(id);
        }
        
        public System.Threading.Tasks.Task DeleteRoomAsync(int id) {
            return base.Channel.DeleteRoomAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.GetRoomResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.GetRoom(PP4.ConsoleTest.ServiceReference1.GetRoomRequest request) {
            return base.Channel.GetRoom(request);
        }
        
        public WebApplication.ServiceReference1.Room GetRoom(int id) {
            PP4.ConsoleTest.ServiceReference1.GetRoomRequest inValue = new PP4.ConsoleTest.ServiceReference1.GetRoomRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.GetRoomRequestBody();
            inValue.Body.id = id;
            PP4.ConsoleTest.ServiceReference1.GetRoomResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).GetRoom(inValue);
            return retVal.Body.GetRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetRoomResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.GetRoomAsync(PP4.ConsoleTest.ServiceReference1.GetRoomRequest request) {
            return base.Channel.GetRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetRoomResponse> GetRoomAsync(int id) {
            PP4.ConsoleTest.ServiceReference1.GetRoomRequest inValue = new PP4.ConsoleTest.ServiceReference1.GetRoomRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.GetRoomRequestBody();
            inValue.Body.id = id;
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).GetRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.GetAllRoomsResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.GetAllRooms(PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequest request) {
            return base.Channel.GetAllRooms(request);
        }
        
        public WebApplication.ServiceReference1.Room[] GetAllRooms() {
            PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequest inValue = new PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequestBody();
            PP4.ConsoleTest.ServiceReference1.GetAllRoomsResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).GetAllRooms(inValue);
            return retVal.Body.GetAllRoomsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetAllRoomsResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.GetAllRoomsAsync(PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequest request) {
            return base.Channel.GetAllRoomsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.GetAllRoomsResponse> GetAllRoomsAsync() {
            PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequest inValue = new PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.GetAllRoomsRequestBody();
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).GetAllRoomsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.AddScheduleResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.AddSchedule(PP4.ConsoleTest.ServiceReference1.AddScheduleRequest request) {
            return base.Channel.AddSchedule(request);
        }
        
        public WebApplication.ServiceReference1.Schedule AddSchedule(System.DateTime Day, bool State) {
            PP4.ConsoleTest.ServiceReference1.AddScheduleRequest inValue = new PP4.ConsoleTest.ServiceReference1.AddScheduleRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.AddScheduleRequestBody();
            inValue.Body.Day = Day;
            inValue.Body.State = State;
            PP4.ConsoleTest.ServiceReference1.AddScheduleResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).AddSchedule(inValue);
            return retVal.Body.AddScheduleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddScheduleResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.AddScheduleAsync(PP4.ConsoleTest.ServiceReference1.AddScheduleRequest request) {
            return base.Channel.AddScheduleAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddScheduleResponse> AddScheduleAsync(System.DateTime Day, bool State) {
            PP4.ConsoleTest.ServiceReference1.AddScheduleRequest inValue = new PP4.ConsoleTest.ServiceReference1.AddScheduleRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.AddScheduleRequestBody();
            inValue.Body.Day = Day;
            inValue.Body.State = State;
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).AddScheduleAsync(inValue);
        }
        
        public void UpdateSchedule(int ID_Schedule, System.DateTime Day, bool State) {
            base.Channel.UpdateSchedule(ID_Schedule, Day, State);
        }
        
        public System.Threading.Tasks.Task UpdateScheduleAsync(int ID_Schedule, System.DateTime Day, bool State) {
            return base.Channel.UpdateScheduleAsync(ID_Schedule, Day, State);
        }
        
        public void DeleteSchedule(int id) {
            base.Channel.DeleteSchedule(id);
        }
        
        public System.Threading.Tasks.Task DeleteScheduleAsync(int id) {
            return base.Channel.DeleteScheduleAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.AddSeatResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.AddSeat(PP4.ConsoleTest.ServiceReference1.AddSeatRequest request) {
            return base.Channel.AddSeat(request);
        }
        
        public WebApplication.ServiceReference1.Seat AddSeat(int ID_Room, string Description_Seat, string Row, int Number, decimal Price) {
            PP4.ConsoleTest.ServiceReference1.AddSeatRequest inValue = new PP4.ConsoleTest.ServiceReference1.AddSeatRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.AddSeatRequestBody();
            inValue.Body.ID_Room = ID_Room;
            inValue.Body.Description_Seat = Description_Seat;
            inValue.Body.Row = Row;
            inValue.Body.Number = Number;
            inValue.Body.Price = Price;
            PP4.ConsoleTest.ServiceReference1.AddSeatResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).AddSeat(inValue);
            return retVal.Body.AddSeatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddSeatResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.AddSeatAsync(PP4.ConsoleTest.ServiceReference1.AddSeatRequest request) {
            return base.Channel.AddSeatAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddSeatResponse> AddSeatAsync(int ID_Room, string Description_Seat, string Row, int Number, decimal Price) {
            PP4.ConsoleTest.ServiceReference1.AddSeatRequest inValue = new PP4.ConsoleTest.ServiceReference1.AddSeatRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.AddSeatRequestBody();
            inValue.Body.ID_Room = ID_Room;
            inValue.Body.Description_Seat = Description_Seat;
            inValue.Body.Row = Row;
            inValue.Body.Number = Number;
            inValue.Body.Price = Price;
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).AddSeatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.UpdateSeatResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.UpdateSeat(PP4.ConsoleTest.ServiceReference1.UpdateSeatRequest request) {
            return base.Channel.UpdateSeat(request);
        }
        
        public void UpdateSeat(int ID_Seat, int ID_Room, string Description_Seat, string Row, int Number, decimal Price) {
            PP4.ConsoleTest.ServiceReference1.UpdateSeatRequest inValue = new PP4.ConsoleTest.ServiceReference1.UpdateSeatRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.UpdateSeatRequestBody();
            inValue.Body.ID_Seat = ID_Seat;
            inValue.Body.ID_Room = ID_Room;
            inValue.Body.Description_Seat = Description_Seat;
            inValue.Body.Row = Row;
            inValue.Body.Number = Number;
            inValue.Body.Price = Price;
            PP4.ConsoleTest.ServiceReference1.UpdateSeatResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).UpdateSeat(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.UpdateSeatResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.UpdateSeatAsync(PP4.ConsoleTest.ServiceReference1.UpdateSeatRequest request) {
            return base.Channel.UpdateSeatAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.UpdateSeatResponse> UpdateSeatAsync(int ID_Seat, int ID_Room, string Description_Seat, string Row, int Number, decimal Price) {
            PP4.ConsoleTest.ServiceReference1.UpdateSeatRequest inValue = new PP4.ConsoleTest.ServiceReference1.UpdateSeatRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.UpdateSeatRequestBody();
            inValue.Body.ID_Seat = ID_Seat;
            inValue.Body.ID_Room = ID_Room;
            inValue.Body.Description_Seat = Description_Seat;
            inValue.Body.Row = Row;
            inValue.Body.Number = Number;
            inValue.Body.Price = Price;
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).UpdateSeatAsync(inValue);
        }
        
        public void DeleteSeat(int id) {
            base.Channel.DeleteSeat(id);
        }
        
        public System.Threading.Tasks.Task DeleteSeatAsync(int id) {
            return base.Channel.DeleteSeatAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PP4.ConsoleTest.ServiceReference1.AddPurchaseResponse PP4.ConsoleTest.ServiceReference1.WebService1Soap.AddPurchase(PP4.ConsoleTest.ServiceReference1.AddPurchaseRequest request) {
            return base.Channel.AddPurchase(request);
        }
        
        public WebApplication.ServiceReference1.Purchase AddPurchase(int ID_Batch, int ID_Person, System.DateTime Date_Purchase) {
            PP4.ConsoleTest.ServiceReference1.AddPurchaseRequest inValue = new PP4.ConsoleTest.ServiceReference1.AddPurchaseRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.AddPurchaseRequestBody();
            inValue.Body.ID_Batch = ID_Batch;
            inValue.Body.ID_Person = ID_Person;
            inValue.Body.Date_Purchase = Date_Purchase;
            PP4.ConsoleTest.ServiceReference1.AddPurchaseResponse retVal = ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).AddPurchase(inValue);
            return retVal.Body.AddPurchaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddPurchaseResponse> PP4.ConsoleTest.ServiceReference1.WebService1Soap.AddPurchaseAsync(PP4.ConsoleTest.ServiceReference1.AddPurchaseRequest request) {
            return base.Channel.AddPurchaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<PP4.ConsoleTest.ServiceReference1.AddPurchaseResponse> AddPurchaseAsync(int ID_Batch, int ID_Person, System.DateTime Date_Purchase) {
            PP4.ConsoleTest.ServiceReference1.AddPurchaseRequest inValue = new PP4.ConsoleTest.ServiceReference1.AddPurchaseRequest();
            inValue.Body = new PP4.ConsoleTest.ServiceReference1.AddPurchaseRequestBody();
            inValue.Body.ID_Batch = ID_Batch;
            inValue.Body.ID_Person = ID_Person;
            inValue.Body.Date_Purchase = Date_Purchase;
            return ((PP4.ConsoleTest.ServiceReference1.WebService1Soap)(this)).AddPurchaseAsync(inValue);
        }
        
        public void UpdatePurchase(int ID_Purchase, int ID_Batch, int ID_Person, System.DateTime Date_Purchase) {
            base.Channel.UpdatePurchase(ID_Purchase, ID_Batch, ID_Person, Date_Purchase);
        }
        
        public System.Threading.Tasks.Task UpdatePurchaseAsync(int ID_Purchase, int ID_Batch, int ID_Person, System.DateTime Date_Purchase) {
            return base.Channel.UpdatePurchaseAsync(ID_Purchase, ID_Batch, ID_Person, Date_Purchase);
        }
        
        public void DeletePurchase(int id) {
            base.Channel.DeletePurchase(id);
        }
        
        public System.Threading.Tasks.Task DeletePurchaseAsync(int id) {
            return base.Channel.DeletePurchaseAsync(id);
        }
    }
}
